databases:
  - name: bangsam
    databaseName: mysite
    user: mysite
    region: singapore

services:
  - type: web
    name: bangsam
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.asgi:application  --worker-class uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bangsam
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
